# SonarCloud Configuration
sonar.host.url=https://sonarcloud.io
sonar.projectKey=jeevanjot011_ScalableComputing
sonar.organization=jeevanjot011-1
sonar.sources=.


# Project info
sonar.projectName=Scalable Financial Calculator Suite
sonar.projectVersion=2.0

# Sources
sonar.sources=eb-website,loan_service
sonar.exclusions=**/*.pyc,**/__pycache__/**,**/node_modules/**

# Python
sonar.python.version=3.9
sonar.python.coverage.reportPaths=eb-website/coverage.xml

# Encoding
sonar.sourceEncoding=UTF-8

# Don't wait for quality gate (for CI/CD)
sonar.qualitygate.wait=false
