sonar.projectKey=jeevanjot011_ScalableComputing
sonar.organization=jeevanjot011
sonar.python.coverage.reportPaths=coverage.xml
sonar.sources=loan_service,eb-website
sonar.tests=tests
sonar.coverage.exclusions=**/tests/**,**/__init__.py
sonar.qualitygate.wait=false